=== GDWG-DEV/GDWG-DEV-GSICS-Products-Checker/NetCDF_Checker/Utils/tests/employees.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="emailType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="type" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:element name="employees">
     <xs:complexType>
      <xs:sequence>
        <xs:element name="employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="firstname" type="xs:string"/>
              <xs:element name="lastname" type="xs:string"/>
              <xs:element name="age" type="xs:string"/>
              <xs:element name="email" type="emailType"/>
            </xs:sequence>
            <xs:attribute name="emplid" type="xs:string" />
            <xs:attribute name="type" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
 
</xs:schema>

=== GDWG-DEV/GDWG-DEV-GSICS-Products-Checker/NetCDF_Checker/Utils/tests/employees.xml
<!--?xml version="1.0"?-->

<employees xsi:noNamespaceSchemaLocation="employees.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <employee emplid="1111" type="admin">
        <firstname>John</firstname>
        <lastname>Watson</lastname>
        <age>30</age>
        <email type="home">johnwatson@sh.com</email>
    </employee>
    <employee emplid="2222" type="admin">
        <firstname>Sherlock</firstname>
        <lastname>Homes</lastname>
        <age>32</age>
        <email type="office">sherlock@sh.com</email>
    </employee>
    <employee emplid="3333" type="user">
        <firstname>Jim</firstname>
        <lastname>Moriarty</lastname>
        <age>52</age>
        <email type="gameTag">jim@sh.com</email>
    </employee>
    <employee emplid="4444" type="user">
        <firstname>Mycroft</firstname>
        <lastname>Holmes</lastname>
        <age>41</age>
        <email type="rubbish">mycroft@sh.com</email>
    </employee>
    
    <!-- Tags below this comment are programmatically generated -->
    
</employees>
